name: Build and Deploy to Nekoweb

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: |
          npm install --save-dev prettier
          npm install sass

      - name: Format files with Prettier
        run: npx prettier --config .prettierrc --write "**/*.{js,jsx,ts,tsx,css,scss,html,json,md}"

      - name: Compile Sass
        run: npx sass scss/app.scss:public/css/index.css --no-source-map

      - name: Remove node_modules and package files
        run: |
          rm -rf node_modules
          rm package.json
          rm package-lock.json

      - name: Commit formatted and compiled files
        uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ github.repository == 'ohitstom/nekoweb' && github.ref == 'refs/heads/main' }}
        with:
          commit_message: "chore: format and compile"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          branch: ${{ github.ref }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch latest commit
        run: git fetch origin main

      - name: Checkout latest commit
        run: git checkout -B main origin/main

      - name: Install dependencies
        run: |
          npm install -g html-minifier uglify-js cssnano-cli

      - name: Prepare build
        run: |
          mkdir -p ./build
          cp -r ./public/* ./build

      - name: Minify HTML files
        run: find build -name "*.html" -exec html-minifier --collapse-whitespace --remove-comments --remove-redundant-attributes --use-short-doctype --minify-css true --minify-js true -o {} {} \;

      - name: Minify JavaScript files
        run: find build -name "*.js" -exec uglifyjs --compress --mangle -o {} -- {} \;

      - name: Minify CSS files
        run: find build -name "*.css" -exec cssnano {} {} \;

      - name: Deploy to Nekoweb
        uses: mp-pinheiro/nekoweb-deploy@main
        with:
          API_KEY: ${{ secrets.NEKOWEB_API_KEY }}
          BUILD_DIR: "./build"
          DEPLOY_DIR: "/"
          CLEANUP: "False"
          DELAY: "0.5"
          NEKOWEB_PAGENAME: "ohitstom"
          ENCRYPTION_KEY: ${{ secrets.NEKOWEB_ENCRYPTION_KEY }}
